### ISSUE TITLE
Bug en misions entregar suministros

### ISSUE THREAD

**Issue by piratajr** [piratajr/DCG#12]
El titulo es demasiado grande
![2015-11-03_00004](https://cloud.githubusercontent.com/assets/13269753/10923399/fa67f6a8-8280-11e5-853d-f5c1f02c1bca.jpg)

**Comment by piratajr** [comment]
Se puede cambiar por "Sumi. Medicos" ? o algo parecido @Nanfer

**Comment by Nanfer** [comment]
Actualizado por Sum. Medicos, queda traducir el texto final al completar una TASK (Los mensajes approval)

**Comment by piratajr** [comment]
Ok cuando lo tengas todo hacemos pull

**Comment by piratajr** [comment]
Hecho
