### ISSUE TITLE
Loadouts fata takistan y altis

### ISSUE THREAD

**Issue by piratajr** [piratajr/DCG#21]
Hacer loadouts para fata, altis y takistan

**Comment by Nanfer** [comment]
Loadout definido para FATA a la espera de commit, está con los slots normales si se han añadido más slots de medico, modificar copiando el loadout de medico ya puesto.

**Comment by piratajr** [comment]
Prepara la base. Pero no pullees hasta que reasignemos slots. Piensa que los slots seran igual que cherna
